
  
server {
    listen              8004;
	server_name woliveir.42.fr www.woliveir.42.fr;
    host 127.0.0.1;
    root    ./configs/;
    index index.html;
    location /0 {
        allow_methods GET GET DELETE GET POST;
    }
    location /1 {
        methods POST GET;
    }
    location /2 {
        allow_methods  DELETE GET POST;
    }
}

server {
    listen     8080          8040;
	server_name woliveir.42.fr www.woliveir.42.fr;
    host 127.0.0.1;
    root    ./configs/;
    index index.html;
    location /0 {
        allow_methods GET GET DELETE GET POST;
    }
    location /1 {
        methods POST GET;
    }
    location /2 {
        allow_methods  DELETE GET POST;
    }
}
