server {
    listen 8000 8001 8002 8003;
    root ;
#    root /var/www/html;
	server_name woliveir.42.fr localhost;
    host 127.0.0.1;
	index index.html;
    max_body_size 10;
    error_page static_pages/error/404.html static_pages/error/500.html;
    location /fixe00/ { # 1 deve possuir index.html na pasta, responde-lo ao cliente 
        index index.html fixe00.html;
        allow_methods DELETE GET POST;
        autoindex off;
        return /fixe01/;
    }
    location /fixe01/ { # 2 não deve possuir index.html na pasta, responder erro 403 (Forbidden) ao cliente 
        return /aIndex/;
        index index.html fixe01.html;
        allow_methods DELETE GET POST;
        autoindex off;
    }
    location /aIndex/ { # 3 não deve possuir index.html na pasta, responder uma página contendo lista dos arquivos na pasta (auto index). 
        index index.html aIndex.html;
        allow_methods DELETE GET POST;
        autoindex on;
    }
    location /delete/ { # 4 deve retornar a página requerida e poder executar o DELETE
        index index.html delete.html;
        allow_methods DELETE GET POST;
        autoindex off;
    }
    location /deleteNot/ { # 5 deve retornar a página requerida, mas retornar página de erro erro 403 (Forbidden) ao cliente caso solicite DELETE.
        index index.html;
        allow_methods GET POST;
        autoindex off;
    }
    location /redi0/ { # deve 6 poder redirecionar para location /red1/
        return /redi1/;
        index index.html;
        allow_methods DELETE GET POST;
        autoindex off;
    }
    location /redi1/ { # deve 7 poder redirecionar para location /fixe00/
        return /fixe00/;
        index index.html;
        allow_methods DELETE GET POST;
        autoindex off;
    }
    location /redi2/ { # deve 8 poder redirecionar para location /fixe10/ que não exite no conf e deve retornar página de error 502 (erro do servidor)
        return /fixe10/;
        index index.html;
        allow_methods DELETE GET POST;
        autoindex off;
    }
    location /bin-cgi/ { # deve 9 chamar o cgi para montagem da página a ser retornada ao cliente
        index cgi.py;
        allow_methods DELETE GET POST;
    }
}
server {
    listen 9000 9001 9002 9003;
    root ;
#    root /var/www/html;
	server_name woliveir.42.fr localhost;
    host 127.0.0.1;
	index index.html;
    error_page static_pages/error/404.html static_pages/error/500.html;
    location /fixe00/ { # deve possuir index.html na pasta, responde-lo ao cliente 
#        index index.html;
#        allow_methods DELETE GET POST;
#        autoindex off;
    }
}

server {
    listen 9000 9001 9002 9003;
    root ;
#    root /var/www/html;
	server_name woliveir.42.fr localhost;
    host 127.0.42.1;
	index index.html;
    error_page static_pages/error/404.html static_pages/error/500.html;
    location /fixe00/ { # deve possuir index.html na pasta, responde-lo ao cliente 
#        index index.html;
#        allow_methods DELETE GET POST;
#        autoindex off;
    }
}