server {
    listen 8000 8001 8002 8003;
    root ;
#    root /var/www/html;
	server_name woliveir.42.fr localhost;
    host 127.0.0.1;
	index index.html;
    max_body_size 1024;
    error_page static_pages/error/404.html static_pages/error/500.html;
}

server {
    listen 8002;
#    root /var/www/html;
	server_name woliveir.42.fr1 localhost1;
    host 127.0.0.1;
	index index.html;
    max_body_size 10;
    root /casa;
#    error_page static_pages/error/404.html static_pages/error/500.html;
    location /fixe01/ { # não deve possuir index.html na pasta, responder erro 403 (Forbidden) ao cliente 
        index index.html fixe01.html;
        allow_methods DELETE GET POST;
        autoindex on;
    }
    location /aIndex/ { # não deve possuir index.html na pasta, responder uma página contendo lista dos arquivos na pasta (auto index). 
        index index.html aIndex.html;
        allow_methods DELETE GET POST;
        autoindex on;
    }
    location /delete/ { # deve retornar a página requerida e poder executar o DELETE
        index index.html delete.html;
        allow_methods DELETE GET POST;
        autoindex off;
    }
    location /redi1/ { # deve poder redirecionar para location /fixe00/
        return /fixe01/;
        index index.html;
        allow_methods DELETE GET POST;
        autoindex off;
    }
    location /redi2/ { # deve poder redirecionar para location /fixe10/ que não exite no conf e deve retornar página de error 502 (erro do servidor)
        return /fixe10/;
        index index.html;
        allow_methods DELETE GET POST;
        autoindex off;
    }
    location /bin-cgi/ { # deve chamar o cgi para montagem da página a ser retornada ao cliente
        index cgi.py;
        allow_methods DELETE GET POST;
    }
}