server {
    listen 8000 8001 8002 8003 8004;
#    root /var/www/html;
	server_name woliveir.42.fr localhost;
    host 127.0.0.42;
	index index.html;
    max_body_size 10;
    error_page errorPage/404.html errorPage/405.html errorPage/408.html errorPage/500.html;
#    location /fixe00/ { # 1 deve possuir index.html na pasta, responde-lo ao cliente 
#        index index-fixe00.html index.html;
#        allow_methods GET POST DELETE;
#        autoindex off;
#    }
}

