server {
#    listen 8000 8001 8002 8003;
    listen 8000;
    root /var/www/html;
	server_name woliveir.42.fr localhost;
    host 127.0.0.42;
	index index.html;
    max_body_size 10;
    error_page errorPage/404.html errorPage/405.html errorPage/408.html errorPage/500.html;
#    error_page errorPage/405.html errorPage/408.html errorPage/500.html errorPage/404.html;
#    error_page errorPage/405.html errorPage/408.html errorPage/500.html;
    location / { # 1 deve possuir index.html na pasta, responde-lo ao cliente 
#        index index.html;
        allow_methods GET POST DELETE;
        autoindex off;
    }
    location /fixe00/ { # 1 deve possuir index.html na pasta, responde-lo ao cliente 
        index index-fixe00.html index.html;
        allow_methods GET POST DELETE;
        autoindex off;
    }
    location /fixe01/ { # 2 deve possuir index.html na pasta, responde-lo ao cliente
        index index.html index-fixe01.html;
        allow_methods DELETE GET POST;
        autoindex off;
    }
    location /aIndex/ { # 3 não deve possuir index.html na pasta, responder uma página contendo lista dos arquivos na pasta (auto index). 
        index index.html index1.html aIndex.html;
        allow_methods DELETE GET POST;
        autoindex on;
    }
    location /aIndex/folder00 { # 3 não deve possuir index.html na pasta, responder uma página contendo lista dos arquivos na pasta (auto index). 
        index folder00.html index.html;
        allow_methods DELETE GET POST;
        autoindex on;
    }
    location /aIndex/folder01 { # 3 não deve possuir index.html na pasta, responder uma página contendo lista dos arquivos na pasta (auto index). 
        index folder01.html index.html;
        allow_methods DELETE GET POST;
        autoindex off;
    }
    location /delete/ { # 4 deve retornar a página requerida e poder executar o DELETE
        index index0.html index1.html index2.html index3.html delete.html;
        allow_methods DELETE GET POST;
        autoindex off;
    }
    location /getNot/ { # 5 deve retornar a página requerida, mas retornar página de erro erro 403 (Forbidden) ao cliente caso solicite DELETE.
        index index.html;
        allow_methods DELETE POST;
        autoindex off;
    }
    location /redi0/ { # deve 6 poder redirecionar para location /red1/
        return /redi1/;
        index index.html;
        allow_methods DELETE GET POST;
        autoindex off;
    }
    location /redi1/ { # deve 7 poder redirecionar para location /fixe00/
        return /fixe00/;
        index index.html;
        allow_methods DELETE GET POST;
        autoindex off;
    }
    location /redi2/ { # deve 8 poder redirecionar para location /fixe10/ que não exite no conf e deve retornar página de error 502 (erro do servidor)
        return /fixe10/;
        index index.html;
        allow_methods DELETE GET POST;
        autoindex off;
    }
    location /redi3/ { # deve 7 poder redirecionar para location /fixe00/
        return /redi4/;
        index index.html;
        allow_methods DELETE GET POST;
        autoindex off;
    }
    location /redi4/ { # deve 8 poder redirecionar para location /fixe10/ que não exite no conf e deve retornar página de error 502 (erro do servidor)
        return /redi3/;
        index index.html;
        allow_methods DELETE GET POST;
        autoindex off;
    }
    location /bin-cgi/ { # deve 9 chamar o cgi para montagem da página a ser retornada ao cliente
        index cgi.py cgi1.py cgi2.py;
        allow_methods DELETE GET POST;
    }
}

